# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36d1b57813af4b73166ba34d7c81da614eef292ca29dde5a2b29810b162efcb2fa9d162123758fdbe2a52b239ce0e7577b11d6143fc43f62bfd995f8d50d3a03

test:
  secret_key_base: 681afe3d2d2dc4f88c8848be77f278752f5a5fbb9b4fb73bc150136b5169aab223c209e5a4abffe8f097bbc303bb81ea014793c81744f9d72116d700c7dafda1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
